### ISSUE TITLE
[Feature]: SQL格式导出的时候支持多条记录合并到一个insert语句

### ISSUE THREAD

**Issue by wangzk0206** [oceanbase/obdumper-loader-doc#13]
### Describe your use case

目前obdumper导出sql格式的数据时，一条记录时一个insert语句，是否可以支持多条记录放到一个insert语句中哪？

### Describe the solution you'd like

目前obdumper导出sql格式的数据时，一条记录时一个insert语句，是否可以支持多条记录放到一个insert语句中哪？

**Comment by chang1sun** [comment]
目前是不支持的。不妨描述下您的使用场景以及需要该功能的原因，我们会考虑的哈！
